# Generated by Django 3.2.9 on 2021-11-20 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20211120_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='projects/standard.png', upload_to='projects/', verbose_name='Изображение'),
        ),
    ]
