# Generated by Django 3.2.9 on 2021-11-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20211122_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(default='projects/standard_project_image1.png', upload_to='projects/', verbose_name='Изображение'),
        ),
    ]
