# Generated by Django 3.2.9 on 2021-11-22 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20211122_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_url',
            field=models.CharField(default=None, max_length=100, verbose_name='ГитХаб проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='additional_image',
            field=models.ImageField(default='projects/additional_project_image.png', upload_to='projects/', verbose_name='Дополнительное изображение'),
        ),
    ]
