# Generated by Django 3.2.9 on 2021-11-22 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20211122_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='github_url',
            field=models.CharField(default='', max_length=100, verbose_name='ГитХаб проекта'),
        ),
    ]
