# Generated by Django 3.2.9 on 2021-11-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_project_github_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='github_url',
            field=models.URLField(verbose_name='ГитХаб проекта'),
        ),
    ]
