# Generated by Django 3.2.9 on 2021-11-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_remove_project_github_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_url',
            field=models.URLField(default='', max_length=100, verbose_name='Ссылка на ГитХаб проекта'),
        ),
    ]
