# Generated by Django 3.2.9 on 2021-11-24 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_project_github_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='image',
            new_name='main_image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='additional_image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='github_url',
        ),
        migrations.AddField(
            model_name='project',
            name='github_video_url',
            field=models.URLField(default='', max_length=160, verbose_name='Ссылка на проект или видео'),
        ),
        migrations.CreateModel(
            name='ProjectImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/', verbose_name='Изображение')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
    ]
