# Generated by Django 3.2.9 on 2022-01-01 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_auto_20211220_0210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
        migrations.RemoveField(
            model_name='projectimages',
            name='project',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectImages',
        ),
    ]
